In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
array = np.array(my_list)

In [5]:
array

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

AttributeError: module 'numpy' has no attribute 'twos'

In [26]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [27]:
np.ones(((3,3,3)))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.98381663, 0.12535591, 0.47695764, 0.29076379, 0.92234131])

In [30]:
np.random.rand(5,5)

array([[0.44880385, 0.7974535 , 0.9045737 , 0.17714653, 0.08763577],
       [0.51121118, 0.676104  , 0.48526423, 0.09596997, 0.09021326],
       [0.90440911, 0.69912829, 0.71709839, 0.38307966, 0.72254843],
       [0.05516417, 0.90240526, 0.4581684 , 0.55944291, 0.50219892],
       [0.70271626, 0.17700635, 0.74809477, 0.26883948, 0.97035274]])

In [31]:
np.random.randn(5)

array([-2.54105147, -0.99486841, -0.45054766,  1.26856852,  2.04333754])

In [32]:
np.random.randn(5,5)

array([[ 1.64383698, -0.81852846,  0.07286072, -0.28267788,  0.1099276 ],
       [ 0.35914301, -0.90590864, -1.03993331,  0.5000286 , -1.11192039],
       [-0.4775089 , -0.05324889, -0.11221882,  1.0247263 ,  2.038009  ],
       [-1.21034073,  0.59606614,  1.17221274, -0.40314671, -1.8431452 ],
       [-0.68818048,  1.70819377,  0.23463267,  2.44836883,  0.15031544]])

In [41]:
np.random.randint(1,100)

38

In [42]:
np.random.randint(1,100,5)

array([53, 94, 72, 16,  8])

In [45]:
arr1 = np.arange(25)

In [48]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr1.min()

0

In [50]:
arr1.max()

24

In [52]:
arr1.argmax()#return index

24

In [53]:
arr1.shape

(25,)

In [54]:
arr = arr1.reshape(5,5)

In [55]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
arr.shape

(5, 5)

In [57]:
arr.dtype

dtype('int64')

In [58]:
from numpy.random import randint

In [59]:
randint(1,5)

2

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[1]

1

In [63]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [64]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[:4]

array([0, 1, 2, 3])

In [68]:
arr[1:5]=100

In [69]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [70]:
slice_of_array = arr[5:9]

In [71]:
slice_of_array

array([5, 6, 7, 8])

In [72]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [73]:
arr_copy = arr.copy()

In [74]:
arr_copy

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [75]:
arr_copy1 = arr_copy

In [76]:
arr_copy1

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [78]:
arr_copy

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [79]:
arr_2d = np.array([[20,15,78],[11,44,30],[4,9,50]])

In [80]:
arr_2d

array([[20, 15, 78],
       [11, 44, 30],
       [ 4,  9, 50]])

In [82]:
arr_2d[1][0]

11

In [83]:
arr_2d[1,0]

11

In [84]:
arr_2d[:2,1:]

array([[15, 78],
       [44, 30]])

In [85]:
arr_2d[:2]

array([[20, 15, 78],
       [11, 44, 30]])

In [88]:
arr = np.arange(0,10)

In [89]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [91]:
boo_arr = arr>5

In [92]:
boo_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [94]:
arr[boo_arr]

array([6, 7, 8, 9])

In [95]:
arr[arr>5]

array([6, 7, 8, 9])

In [96]:
arr[arr<4]

array([0, 1, 2, 3])

In [97]:
arr_2d = np.arange(50).reshape(5,10)

In [98]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [102]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [103]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [105]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [107]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [108]:
arr*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [109]:
arr/arr

/home/robot/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [110]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [111]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [112]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [113]:
np.max(arr)

9

In [115]:
np.min(arr)

0

In [116]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219
